/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 * Author Mohamed Mokadem
 */

package machine_piquage;




import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import static java.lang.Math.floor;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;




/**
 *
 * @author Mohamed mokadem
 */
public class window extends javax.swing.JFrame{
    Recup r = new Recup();
    protected String line=null;
    protected String avantvirugile;
    protected String apresvirugile;
    protected int i=0;
    protected String[] array = new String[20000];
    protected String nextline=null;
    protected String avantvirugile_next;
    protected String apresvirugile_next;
    protected String avantvirugile_p;
    protected String apresvirugile_p;
    protected float vecteur_ux;
    protected float vecteur_uy;
    public float vecteur_ux_next;
    public float vecteur_uy_next;
    float Z;
    float produit_scalaire=0;
    float norme = 0;
    float norme_next = 0;
    float produit_norme = 0;
    float produit_vectoriel = 0;
    float teta_rad = 0;
    float teta_deg = 0;
    int step = 0;
    int S = 0;
    float produit_vectoriel_next=0;
    List< Integer> listS = new ArrayList< Integer>();
    List< String> listline = new ArrayList< String>();
    List< Float> listP = new ArrayList< Float>();
    String depot_fil;
    int count = 0;

    
    
    BufferedReader in;
    
    /**
     * Creates new form window
     */


    public window() {
        initComponents();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Charger les points");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );

        jLabel2.setText("file name: ");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel3.setText("Gcode: ");

        jLabel4.setText("Longeur fils consommer par piquage:");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 764, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
        );

        jButton2.setText("Save as");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1065, 1065, 1065)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(121, 121, 121))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addComponent(jLabel1)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jButton2)
                        .addGap(2890, 2890, 2890)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void calculZ(float fil){

    if(i != 0){
    
    vecteur_ux = Float.parseFloat(avantvirugile) - Float.parseFloat(array[i-1].split(",")[0]);
    vecteur_uy = Float.parseFloat(apresvirugile) - Float.parseFloat(array[i-1].split(",")[1]);

    float pas = (float) -(Math.sqrt(Math.pow(this.vecteur_ux,2)+Math.pow(this.vecteur_uy,2)));
    Z = (float) floor(-(fil - pas));
    }
    
}
    
    public void calculS(){
        
        vecteur_ux_next = Float.parseFloat(avantvirugile_next) - Float.parseFloat(avantvirugile);
        vecteur_uy_next = Float.parseFloat(apresvirugile_next) - Float.parseFloat(apresvirugile);
        
        this.produit_scalaire = (vecteur_ux*vecteur_ux_next) + (vecteur_uy*vecteur_uy_next);
        norme = (float) Math.sqrt(Math.pow(this.vecteur_ux, 2) + Math.pow(this.vecteur_uy, 2));
        norme_next = (float) Math.sqrt(Math.pow(this.vecteur_ux_next, 2) + Math.pow(this.vecteur_uy_next, 2));
        this.produit_norme = norme * norme_next;
        
        this.produit_vectoriel= (this.vecteur_ux*this.vecteur_uy_next)-(this.vecteur_ux_next*this.vecteur_uy_next);
        this.teta_rad = (float)Math.acos(this.produit_scalaire/this.produit_norme);
        this.teta_deg = (float) ((float)(this.teta_rad*180)/Math.PI);
        
        
        this.step = Math.round((this.teta_deg*200)/360);
        listS.add(this.step);
        listP.add(this.produit_vectoriel);
        
        if(listS.size()>=3 && listP.size()>=3){
            int k = listS.size()-2;
            int x = listP.size()-2;
            produit_vectoriel_next = listP.get(x);
            
            if(this.produit_vectoriel_next<0){
                S = -listS.get(k);
                
            }else{
                S = listS.get(k);
            }
        }else{
            S=0;
            produit_vectoriel_next = 0;
        }
}
    
    
    
    public void graphe(){
        
              XYSeries series = new XYSeries("XYGraph",false,true);
        
                        for(i=0;i<this.listline.toArray().length;i++){
                        Float X = Float.parseFloat(listline.toArray()[i].toString().split(",")[0]);
                        Float Y  = Float.parseFloat(listline.toArray()[i].toString().split(",")[1]);
                        series.add(X, Y);
                        }

   XYSeriesCollection dataset = new XYSeriesCollection();
   dataset.addSeries(series);
        
   JFreeChart chart = ChartFactory.createXYLineChart(
   "XY Chart", // Title
   "x-axis", // x-axis Label
   "y-axis", // y-axis Label
   dataset, // Dataset
   PlotOrientation.VERTICAL, // Plot Orientation
   true, // Show Legend
   true, // Use tooltips
   false // Configure chart to generate URLs?
);
    
        chart.setBackgroundPaint(Color.YELLOW);
        chart.getTitle().setPaint(Color.RED);
        XYPlot plot = chart.getXYPlot();
        XYLineAndShapeRenderer renderer = new XYLineAndShapeRenderer();
        plot.setRenderer(renderer);
        ChartPanel CP = new ChartPanel(chart);
       
        CP.setSize(this.jPanel1.getWidth(), this.jPanel1.getHeight());
        CP.setVisible(true);
        jPanel1.remove(CP);
        jPanel1.add(CP);
        this.jPanel1.revalidate();
        jPanel1.repaint();
}
    
    

    

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        i=0;
        this.jTextArea1.setText("");
        this.depot_fil = this.jTextField1.getText();
        JFileChooser chooser =  new JFileChooser();

        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename=f.getName();
        this.jLabel2.setText("File name: " + filename);
        
        this.jTextArea1.setText("G21 G40 \n");

        try {
            in = new BufferedReader(new FileReader(f));
            while((line = in.readLine())  != null){
              array[i] = line;
              listline.add(line);
              this.avantvirugile = array[i].split(",")[0];
              this.apresvirugile = array[i].split(",")[1];
              
              calculZ(Float.parseFloat(this.depot_fil));
              in.mark(9);
              if((nextline = in.readLine()) != null){
              this.avantvirugile_next = nextline.split(",")[0];
              this.apresvirugile_next = nextline.split(",")[1]; 
              in.reset();
              }
              calculS();
              if(i!=0)
              {
                    this.jTextArea1.append("G91 G0 S"+ this.S + "Z "+ this.Z +" \nM2 \n");
                    this.jTextArea1.append("G90 G0 X" + avantvirugile + " Y" + apresvirugile + "\n" + "M2\nA\nG4 P4 \n\n");
              }
            i++;
            }
            listline.toArray();
            graphe();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(window.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(window.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    public void SaveAs() throws IOException {
        
     final JFileChooser fc = new JFileChooser();

      final JFileChooser SaveAs = new JFileChooser();
      SaveAs.setApproveButtonText("Save");
      int actionDialog = SaveAs.showOpenDialog(this);
      if (actionDialog != JFileChooser.APPROVE_OPTION) {
         return;
      }

      File fileName = new File(SaveAs.getSelectedFile() + ".txt");
      BufferedWriter outFile = null;
      outFile = new BufferedWriter(new FileWriter(fileName));
      this.jTextArea1.write(outFile);   // *** here: ***
      if (outFile != null) {
          outFile.close(); // one of the few times that I think that it's OK
        // to leave this blank
      }
   }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            SaveAs();
        } catch (IOException ex) {
            Logger.getLogger(window.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed




    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
            

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}

